---
- name: Run date, hostname, pwd, and ls commands locally
  hosts: localhost
  tasks:
    - name: Get current date and time
      command: date
      register: date_output

    - name: Display the date and time
      debug:
        msg: "Current date and time: {{ date_output.stdout }}"

    - name: Get current working directory
      command: pwd
      register: pwd_output

    - name: Display the working directory
      debug:
        msg: "Current working directory: {{ pwd_output.stdout }}"

    - name: List all files and folders in the current directory
      command: ls -la
      register: ls_output

    - name: Display the list of files and folders
      debug:
        msg: "Files and folders: {{ ls_output.stdout }}"
