# test_facts.yml
---
- hosts: all
  tasks:
    - name: Collect Facts
      ansible.builtin.setup:
    - name: Output Variables
      ansible.builtin.set_stats:
        data:
          check_name: "{{ ansible_facts.service_mgr }}"
          check_status: "{{ check_status }}"
