---
- name: Disco Playbook
  hosts: all
  vars:
    discousers: "{{ usernames | split(',') | map('trim') | list }}"
    activeusers:
      - fred
      - bob
  tasks:
    - name: Get Users to Disco
      ansible.builtin.set_fact:
        disco_conn_users: "{{ discousers | select('in', activeusers) | list }}"
    - name: Disco Debug Users
      ansible.builtin.debug:
        msg: "{{ discousers }}"
    - name: Disco Debug Disco Users
      ansible.builtin.debug:
        msg: "{{ disco_conn_users }}"
    - name: Disco Stats
      ansible.builtin.set_stats:
        data:
          response:
            usernames: "{{ usernames }}"
            discousers: "{{ disco_conn_users }}"
